version: '3'
services:

  nginx-proxy:
    container_name: felixmind.nginx-proxy
    image: "nginx:alpine"
    volumes:
      - ./docker-config/nginx-proxy/:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - nginx-application
    depends_on:
      - nginx-application

  nginx-application:
    container_name: felixmind.application
    image: "nginx:alpine"
    volumes:
      - ./application:/var/www
      - ./docker-config/nginx-main/:/etc/nginx/conf.d
    ports:
      - "8000:8000"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker-config/php
      dockerfile: Dockerfile
    container_name: felixmind.php-fpm
    image: "php:7.1-fpm"
    volumes:
      - ./application:/var/www
    ports:
    - "9000"

  postgres:
    container_name: felixmind.database
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbtest

  composer:
    container_name: felixmind.composer
    command: install
    image: "composer:2.0"
    volumes:
      - ./application:/app
